name: CI
on:
  pull_request:
    branches: [ "main" ]
jobs:      
  packer_init_validate:
    runs-on: ubuntu-latest
    name: Validate Packer
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: unzip folders
        run: |
          zip -r a5.zip ./
          pwd ./a5
      - name: Validate Packer
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ami.pkr.hcl

